name: Deployment
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: yarn install
    - name: Rebuild yarn packages
      run: yarn rebuild
    - name: Deploy Artifacts
      run: yarn deploy
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
