name: Deployment
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 15
          
      - name: Install Packages
        run: yarn install
      
      - name: Prebuild
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          SKIP_PREFLIGHT_CHECK: ${{ secrets.SKIP_PREFLIGHT_CHECK }}
        run: |
          yarn prebuild

      - name: Build MAC
        if: matrix.os == 'macos-latest'
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          yarn deploy:mac