name: Deployment
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [15.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: yarn install
    - name: Rebuild yarn packages
      run: yarn rebuild
    - name: Prebuild
      run: yarn prebuild
    - name: Deploy Artifacts
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: yarn build && yarn deploy
